In [48]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import string
import pandas as pd

In [ ]:
URL = 'https://books.toscrape.com/catalogue/'
response = requests.get(URL)

In [3]:
soup = BeautifulSoup(response.text, 'html.parser')

In [4]:
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [8]:
raw_books = soup.findAll('article', class_ = 'product_pod')

C:\Users\mmoed\AppData\Local\Temp\ipykernel_17668\2504786083.py:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  raw_books = soup.findAll('article', class_ = 'product_pod')

In [ ]:
print(len(raw_books))

20

In [37]:
"Mohammed: Talal".translate(str.maketrans('','',string.punctuation))

'Mohammed Talal'

In [61]:
Books_list = []
page_num = 1
url = URL
while url and page_num <= 5:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    raw_books = soup.findAll('article', class_ = 'product_pod')
    for item in raw_books:
        name = item.find('h3').find('a')['title']
        rating = item.find('p', class_= 'star-rating')['class'][1]
        price = item.find('p', class_= 'price_color').text
        image_src = item.find('img')['src']
        cleaned_name = name.translate(str.maketrans('','',string.punctuation))
        # Downlaod images
        image_url = urljoin(URL,image_src)
        img_content = requests.get(image_url).content
        with open('../images/' + cleaned_name.replace(" ", "_")[:30] + '.png', "wb") as file:
            file.write(img_content)
        Books_list.append({
            "name": name,
            "rating": rating,
            "price": price,
            "img_url": image_url,
        })
    nxt_btn = soup.find('li', class_ = 'next')
    page_num += 1
    url =f'https://books.toscrape.com/catalogue/page-{page_num}.html' if nxt_btn else None

C:\Users\mmoed\AppData\Local\Temp\ipykernel_17668\434006643.py:7: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  raw_books = soup.findAll('article', class_ = 'product_pod')

KeyboardInterrupt:

In [59]:
df = pd.DataFrame(Books_list)

In [54]:
df.to_csv('../data/raw_data.csv')

In [63]:
df = pd.read_csv('../data/raw_data.csv')
df.sample(10)

,Unnamed: 0,name,rating,price,img_url
21,21,How Music Works,Two,Â£37.32,https://books.toscrape.com/media/cache/5c/c8/5...
70,70,The Art Forger,Three,Â£40.76,https://books.toscrape.com/media/cache/70/fa/7...
76,76,"Saga, Volume 6 (Saga (Collected Editions) #6)",Three,Â£25.02,https://books.toscrape.com/media/cache/43/ae/4...
47,47,Untitled Collection: Sabbath Poems 2014,Four,Â£14.27,https://books.toscrape.com/media/cache/f9/3b/f...
19,19,It's Only the Himalayas,Two,Â£45.17,https://books.toscrape.com/media/cache/27/a5/2...
37,37,"In a Dark, Dark Wood",One,Â£19.63,https://books.toscrape.com/media/cache/23/85/2...
25,25,Birdsong: A Story in Pictures,Three,Â£54.64,https://books.toscrape.com/media/cache/af/6e/a...
16,16,Olio,One,Â£23.88,https://books.toscrape.com/media/cache/55/33/5...
84,84,Patience,Three,Â£10.16,https://books.toscrape.com/media/cache/01/72/0...
44,44,Without Borders (Wanderlove #1),Two,Â£45.07,https://books.toscrape.com/media/cache/24/e2/2...

In [69]:
df['price'] = df['price'].str.replace('Â£', '')
df['price'] = df['price'].astype(float)

In [75]:
df['rating'] = df['rating'].map({'Three': 3,
                   'One': 1,
                    'Four' : 4,
                    'Five': 5,
                    'Two': 2
                    })

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   name        100 non-null    str
 2   rating      100 non-null    int64
 3   price       100 non-null    float64
 4   img_url     100 non-null    str
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 KB

In [ ]:
df.sort_values(by=['rating'], inplace=)

,Unnamed: 0,name,rating,price,img_url
1,1,Tipping the Velvet,1,53.74,https://books.toscrape.com/media/cache/26/0c/2...
2,2,Soumission,1,50.10,https://books.toscrape.com/media/cache/3e/ef/3...
5,5,The Requiem Red,1,22.65,https://books.toscrape.com/media/cache/68/33/6...
9,9,The Black Maria,1,52.15,https://books.toscrape.com/media/cache/58/46/5...
17,17,Mesaerion: The Best Science Fiction Stories 18...,1,37.59,https://books.toscrape.com/media/cache/09/a3/0...
...,...,...,...,...,...
72,72,The Activist's Tao Te Ching: Ancient Advice fo...,5,32.24,https://books.toscrape.com/media/cache/96/db/9...
80,80,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",5,13.61,https://books.toscrape.com/media/cache/78/0b/7...
81,81,Princess Between Worlds (Wide-Awake Princess #5),5,13.34,https://books.toscrape.com/media/cache/b7/e8/b...
65,65,The Inefficiency Assassin: Time Management Tac...,5,20.59,https://books.toscrape.com/media/cache/75/dc/7...
98,98,Join,5,35.67,https://books.toscrape.com/media/cache/93/63/9...

In [78]:
df[df.rating == 1]

,Unnamed: 0,name,rating,price,img_url
1,1,Tipping the Velvet,1,53.74,https://books.toscrape.com/media/cache/26/0c/2...
2,2,Soumission,1,50.10,https://books.toscrape.com/media/cache/3e/ef/3...
5,5,The Requiem Red,1,22.65,https://books.toscrape.com/media/cache/68/33/6...
9,9,The Black Maria,1,52.15,https://books.toscrape.com/media/cache/58/46/5...
16,16,Olio,1,23.88,https://books.toscrape.com/media/cache/55/33/5...
17,17,Mesaerion: The Best Science Fiction Stories 18...,1,37.59,https://books.toscrape.com/media/cache/09/a3/0...
20,20,In Her Wake,1,12.84,https://books.toscrape.com/media/cache/5d/72/5...
33,33,The Bear and the Piano,1,36.89,https://books.toscrape.com/media/cache/cf/bb/c...
37,37,"In a Dark, Dark Wood",1,19.63,https://books.toscrape.com/media/cache/23/85/2...
45,45,When We Collided,1,31.77,https://books.toscrape.com/media/cache/08/04/0...
50,50,"Unbound: How Eight Technologies Made Us Human,...",1,25.52,https://books.toscrape.com/media/cache/4a/3b/4...
51,51,Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRo...,1,16.28,https://books.toscrape.com/media/cache/36/df/3...
55,55,The Torch Is Passed: A Harding Family Story,1,19.09,https://books.toscrape.com/media/cache/33/e5/3...
56,56,The Secret of Dreadwillow Carse,1,56.13,https://books.toscrape.com/media/cache/c4/a2/c...
57,57,The Pioneer Woman Cooks: Dinnertime: Comfort C...,1,56.41,https://books.toscrape.com/media/cache/b7/f4/b...
66,66,The Gutsy Girl: Escapades for Your Life of Epi...,1,37.13,https://books.toscrape.com/media/cache/64/15/6...
67,67,The Electric Pencil: Drawings from Inside Stat...,1,56.06,https://books.toscrape.com/media/cache/2e/23/2...
71,71,The Age of Genius: The Seventeenth Century and...,1,19.73,https://books.toscrape.com/media/cache/2d/4e/2...
82,82,"Pop Gun War, Volume 1: Gift",1,18.97,https://books.toscrape.com/media/cache/c8/2f/c...
86,86,orange: The Complete Collection 1 (orange: The...,1,48.41,https://books.toscrape.com/media/cache/03/88/0...
87,87,Online Marketing for Busy Authors: A Step-By-S...,1,46.35,https://books.toscrape.com/media/cache/ea/9b/e...
96,96,"Layered: Baking, Building, and Styling Spectac...",1,40.11,https://books.toscrape.com/media/cache/98/d1/9...